/** Shared material colors only. Merchant accents, fonts and geometry stay local. */
export const NEUMORPHIC_THEME = {
  light: {
    "--aacp-bg": "#edf0ee",
    "--aacp-surface": "#edf0ee",
    "--aacp-surface-2": "#e8ede9",
    "--aacp-surface-3": "#e0e7e2",
    "--aacp-fg": "#202b24",
    "--aacp-accent-text": "color-mix(in oklab, var(--aacp-accent, #268235) 82%, var(--aacp-fg))",
    "--aacp-muted": "#53645a",
    "--aacp-faint": "#59695f",
    "--aacp-line": "#c9d3cc",
    "--aacp-line-strong": "#c2cec5",
    "--aacp-neu-control-line": "#7c8e81",
    "--aacp-card": "#f0f3f1",
    "--aacp-chip": "#edf0ee",
    "--aacp-success": "#187044",
    "--aacp-panel-bg": "#edf0ee",
    "--aacp-shell-bg": "#edf0ee",
    "--aacp-header-bg": "#edf0ee",
    "--aacp-inset-bg": "#e9eeeb",
    "--aacp-sheet": "#edf0ee",
    "--aacp-surface-elevated": "#f0f3f1",
    "--aacp-shadow-sm": "var(--aacp-neu-raised-sm)",
    "--aacp-shadow-md": "var(--aacp-neu-raised-md)",
    "--aacp-shadow-lg": "var(--aacp-neu-overlay)",
  },
  dark: {
    "--aacp-bg": "#191f1d",
    "--aacp-surface": "#1d2421",
    "--aacp-surface-2": "#191f1d",
    "--aacp-surface-3": "#28332d",
    "--aacp-fg": "#edf3ee",
    "--aacp-accent-text": "color-mix(in oklab, var(--aacp-accent, #268235) 66%, var(--aacp-fg))",
    "--aacp-muted": "#b0beb5",
    "--aacp-faint": "#99aa9f",
    "--aacp-line": "#37483e",
    "--aacp-line-strong": "#455b4c",
    "--aacp-neu-control-line": "#6c8274",
    "--aacp-card": "#202923",
    "--aacp-chip": "#1d2421",
    "--aacp-success": "#68d69c",
    "--aacp-panel-bg": "#1d2421",
    "--aacp-shell-bg": "#191f1d",
    "--aacp-header-bg": "#1d2421",
    "--aacp-inset-bg": "#202623",
    "--aacp-sheet": "#1d2421",
    "--aacp-surface-elevated": "#28332d",
    "--aacp-shadow-sm": "var(--aacp-neu-raised-sm)",
    "--aacp-shadow-md": "var(--aacp-neu-raised-md)",
    "--aacp-shadow-lg": "var(--aacp-neu-overlay)",
  },
} as const;
