import test from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { PrismaClient } from "@prisma/client";
import { ReturnOrderService } from "./return-order.service.js";
import { ReturnAttachmentService } from "./return-attachment.service.js";
import { ReturnCaseService } from "./return-case.service.js";
import { ProcessRefundUseCase } from "./use-cases/process-refund.use-case.js";
import { PrismaReturnRepository } from "../infrastructure/repositories/prisma-return.repository.js";
import { PrismaSupportTicketRepository } from "../../support/infrastructure/prisma-support-ticket.repository.js";
import { UpdateSupportTicketStatusUseCase } from "../../support/application/update-support-ticket-status.use-case.js";
import { SendTicketMessageUseCase } from "../../support/application/send-ticket-message.use-case.js";
import { RealtimeCapabilityService } from "../../../shared/auth/realtime-capability.js";

test("database lifecycle: concurrent opening, ownership, ordered messages, private photos and one financial attempt", { skip: !process.env.RETURNS_DATABASE_TEST }, async t => {
  const database = new URL(process.env.DATABASE_URL!);
  assert.equal(database.hostname, "127.0.0.1"); assert.equal(database.port, "56526"); assert.equal(database.pathname, "/returns_qa");
  const db = new PrismaClient(); const suffix = randomUUID(); const merchantId = `qa_${suffix}`, buyerId = `buyer_${suffix}`, orderId = `order_${suffix}`;
  t.after(async () => {
    const tickets = await db.supportTicket.findMany({ where: { merchantId }, select: { id: true } });
    await db.supportTicketMessage.deleteMany({ where: { ticketId: { in: tickets.map(item => item.id) } } });
    await db.supportAttachment.deleteMany({ where: { merchantId } }); await db.supportTicket.deleteMany({ where: { merchantId } });
    await db.return.deleteMany({ where: { merchantId } }); await db.buyerPurchaseRecord.deleteMany({ where: { merchantId } });
    await db.completedOrder.deleteMany({ where: { merchantId } }); await db.paymentIntent.deleteMany({ where: { merchantId } });
    await db.outboxMessage.deleteMany({ where: { merchantId } }); await db.checkoutSession.deleteMany({ where: { merchantId } }); await db.$disconnect();
  });
  const items = [{ variantId: "variant_a", name: "Item A", quantity: 2, unitPriceCents: 1000 }, { variantId: "variant_b", name: "Item B", quantity: 1, unitPriceCents: 900 }];
  await db.checkoutSession.create({ data: { merchantId, sessionId: suffix, globalUserId: buyerId, conversationId: suffix, cart: { items }, createdAt: new Date(), updatedAt: new Date() } });
  await db.buyerPurchaseRecord.create({ data: { merchantId, globalUserId: buyerId, orderId, currency: "BRL", totalAmount: 29, discountAmount: 0, completedAt: new Date(), items } });
  await db.completedOrder.create({ data: { merchantId, sessionId: suffix, externalOrderId: orderId, orderTotal: 29, currency: "BRL", lineItemsJson: items, completedAt: new Date() } });
  await db.paymentIntent.create({ data: { id: `pay_${suffix}`, merchantId, sessionId: suffix, idempotencyKey: suffix, amountCents: 2900, currency: "BRL", method: "card", status: "approved", providerPaymentId: `provider_${suffix}`, creation: { input: { provider: "stripe" } } } });
  const storage = new Map<string, Buffer>();
  const caps = new RealtimeCapabilityService("test-conversation-return-secret-with-32-characters");
  const photos = new ReturnAttachmentService(db, { isConfigured: () => true, uploadPrivate: async (bytes: Buffer, key: string) => { storage.set(key, bytes); }, readPrivate: async (key: string) => storage.get(key)! } as any, caps);
  const orders = new ReturnOrderService(db); let posts = 0, settled = false;
  const refund = new ProcessRefundUseCase(new PrismaReturnRepository(db), { refundOrderPayment: async (input: any) => { posts++; assert.equal(input.amountCents, 1000); assert.equal(await db.returnRefund.count({ where: { return: { merchantId }, amountInCents: 1000, status: "PENDING" } }), 1); return { refunded: false, amountCents: 1000, paymentIntentId: `pay_${suffix}`, providerRefundId: `refund_${suffix}`, reason: "provider_refund_pending" }; }, reconcileRefundPayment: async () => ({ state: settled ? "succeeded" : "unknown" }) } as any, db, orders);
  const cases = new ReturnCaseService(db, orders, photos, refund, {} as any, caps);
  const input = { merchantId, buyerId, orderId, reason: "DEFECTIVE", notes: "Uma unidade chegou com defeito.", requestKey: randomUUID(), items: [{ variantId: "variant_a", quantity: 1 }] };
  await assert.rejects(() => cases.open({ ...input, buyerId: "another_buyer" }), /buyer_order_not_found/);
  await assert.rejects(() => cases.open({ ...input, items: [{ variantId: "foreign", quantity: 1 }] }), /item_not_in_order/);
  await assert.rejects(() => cases.open({ ...input, items: [{ variantId: "variant_a", quantity: 3 }] }), /invalid_return_quantity/);
  const opened = await Promise.all(Array.from({ length: 8 }, () => cases.open(input)));
  const ticketId = opened[0]!.ticketId; const returnId = opened[0]!.returnId;
  assert.equal(new Set(opened.map(item => item.ticketId)).size, 1); assert.equal(await db.return.count({ where: { merchantId } }), 1); assert.equal(await db.supportTicket.count({ where: { merchantId } }), 1);
  assert.equal((await cases.detail(merchantId, ticketId)).messages.length, 2);
  assert.equal((await cases.open({ ...input, requestKey: randomUUID() })).ticketId, ticketId);
  await assert.rejects(() => cases.buyerTicket("another_buyer", ticketId), /ticket_not_found/);
  await assert.rejects(() => cases.detail("another_merchant", ticketId), /ticket_not_found/);
  const update = new UpdateSupportTicketStatusUseCase(new PrismaSupportTicketRepository(db), db);
  await update.execute(merchantId, ticketId, "in_progress", "operator_qa"); await update.execute(merchantId, ticketId, "in_progress", "operator_qa");
  assert.equal((await cases.detail(merchantId, ticketId)).messages.length, 3);
  await assert.rejects(() => update.execute(merchantId, ticketId, "resolved"), /resolve_return_before_closing_ticket/);
  const send = new SendTicketMessageUseCase(db); const key = randomUUID();
  const replies = await Promise.all(Array.from({ length: 5 }, () => send.execute({ merchantId, ticketId, content: "Estou analisando o item A.", senderType: "merchant", clientMessageId: key })));
  assert.equal(new Set(replies.map(item => item.id)).size, 1);
  const aliasId = `sup_alias_${suffix}`;
  await db.supportTicket.create({ data: { id: aliasId, merchantId, buyerId, returnId, mergedIntoId: ticketId, buyerMessage: "Chamado antigo duplicado", source: "return_request", status: "closed", createdAt: new Date(), updatedAt: new Date() } });
  const aliasReply = await send.execute({ merchantId, ticketId: aliasId, content: "Estou analisando o item A.", senderType: "merchant", clientMessageId: key });
  assert.equal(aliasReply.ticketId, ticketId); assert.equal(aliasReply.id, replies[0]!.id);
  assert.equal(await db.supportTicketMessage.count({ where: { ticketId: aliasId } }), 0);
  let detail = await cases.detail(merchantId, ticketId); assert.ok(detail.unreadCount >= 2);
  await cases.markRead(merchantId, ticketId, "buyer", detail.messages.at(-1)!.id);
  assert.equal((await cases.detail(merchantId, ticketId)).unreadCount, 0);
  const png = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aF9sAAAAASUVORK5CYII=";
  await cases.sendPhotos(merchantId, ticketId, buyerId, "Foto do defeito", [png], randomUUID());
  detail = await cases.detail(merchantId, ticketId); const photoUrl = new URL(detail.imageUrls[0]!, "http://localhost"); const attachmentId = photoUrl.pathname.split("/").at(-1)!;
  assert.equal((await photos.read(attachmentId, photoUrl.searchParams.get("access_token")!)).contentType, "image/png");
  assert.ok(![...storage.values()][0]!.subarray(0, 8).equals(Buffer.from(png.split(",")[1]!, "base64").subarray(0, 8)));
  await assert.rejects(() => photos.read("different_id", photoUrl.searchParams.get("access_token")!), /attachment_not_found/);
  const databasePhotos = new ReturnAttachmentService(db, { isConfigured: () => false,
    uploadPrivate: async () => { throw new Error("Database photos must not call object storage"); },
    readPrivate: async () => { throw new Error("Database photos must not call object storage"); } } as any, caps);
  const databaseCases = new ReturnCaseService(db, orders, databasePhotos, refund, {} as any, caps);
  const photoMessageKey = randomUUID();
  await Promise.all(Array.from({ length: 3 }, () => databaseCases.sendPhotos(merchantId, ticketId, buyerId, "Foto privada no banco", [png], photoMessageKey)));
  assert.equal(await db.supportTicketMessage.count({ where: { ticketId, clientMessageId: photoMessageKey } }), 1);
  const storedPhoto = await db.supportAttachment.findFirstOrThrow({ where: { ticketId, storageKey: { startsWith: "database:" } } });
  assert.ok(storedPhoto.encryptedPayload);
  assert.notDeepEqual(Buffer.from(storedPhoto.encryptedPayload!), Buffer.from(png.split(",")[1]!, "base64"));
  assert.equal(await db.supportAttachment.count({ where: { ticketId, storageKey: { startsWith: "database:" } } }), 1);
  const databaseUrl = new URL(databasePhotos.urls([storedPhoto.id], merchantId)[0]!, "http://localhost");
  assert.deepEqual((await databasePhotos.read(storedPhoto.id, databaseUrl.searchParams.get("access_token")!)).buffer, Buffer.from(png.split(",")[1]!, "base64"));
  const foreignToken = caps.issue({ purpose: "support-attachment", merchantId: "another_merchant", resourceId: storedPhoto.id }).token;
  await assert.rejects(() => databasePhotos.read(storedPhoto.id, foreignToken), /attachment_not_found/);
  const beforeReply = detail.messages.at(-1)!.id; await send.execute({ merchantId, ticketId, content: "Recebi a foto.", senderType: "merchant", clientMessageId: randomUUID() }); await cases.markRead(merchantId, ticketId, "buyer", beforeReply);
  assert.equal((await cases.detail(merchantId, ticketId)).unreadCount, 1);
  for (let index = 0; index < 105; index++) await cases.sendPhotos(merchantId, ticketId, buyerId, `Mensagem ${index}`, [], randomUUID());
  const firstPage = await cases.detail(merchantId, ticketId); assert.equal(firstPage.messages.length, 100); assert.ok(firstPage.nextCursor);
  const secondPage = await cases.detail(merchantId, ticketId, firstPage.nextCursor!); const all = [...firstPage.messages, ...secondPage.messages];
  assert.equal(new Set(all.map(item => item.id)).size, all.length); assert.ok(all.length > 100);
  for (let index = 1; index < all.length; index++) assert.ok(all[index]!.createdAt > all[index - 1]!.createdAt);
  const preview = await orders.preview(merchantId, returnId); assert.equal(preview.amountCents, 1000);
  await assert.rejects(() => cases.approveRefund(merchantId, ticketId, 2900), /refund_preview_changed/);
  await Promise.all(Array.from({ length: 5 }, () => cases.approveRefund(merchantId, ticketId, 1000))); assert.equal(posts, 1);
  detail = await cases.detail(merchantId, ticketId); assert.equal(detail.active, true); assert.equal(detail.refund?.status, "PENDING");
  assert.equal(await db.returnNoticeDelivery.count({ where: { returnId, type: "return_approved" } }), 2);
  await assert.rejects(() => cases.action(merchantId, ticketId, "operator_qa", { action: "reject", notes: "Conflito" }), /case_cannot_change_during_refund/);
  settled = true; await cases.approveRefund(merchantId, ticketId, 1000); detail = await cases.detail(merchantId, ticketId);
  assert.equal(detail.active, false); assert.equal(detail.refund?.status, "COMPLETED"); assert.equal(detail.status, "resolved"); assert.equal(posts, 1);
  await assert.rejects(() => cases.sendPhotos(merchantId, ticketId, buyerId, "Outra mensagem", [], randomUUID()), /ticket_resolved/);
  assert.equal(await db.returnNoticeDelivery.count({ where: { returnId, type: "return_refunded" } }), 2);
  const remaining = await orders.load(merchantId, orderId, buyerId); assert.equal(remaining.items.find(item => item.variantId === "variant_a")?.eligibleQuantity, 1);
  const next = await cases.open({ ...input, requestKey: randomUUID(), items: [{ variantId: "variant_a", quantity: 1 }, { variantId: "variant_b", quantity: 1 }] });
  assert.notEqual(next.ticketId, ticketId); assert.equal((await orders.preview(merchantId, next.returnId)).amountCents, 1900);
  // Recover an older ticket closed while its return was still active.
  await db.supportTicket.update({ where: { id: next.ticketId }, data: { status: "closed" } });
  assert.equal((await cases.open({ ...input, requestKey: randomUUID() })).ticketId, next.ticketId);
  assert.equal((await cases.detail(merchantId, next.ticketId)).status, "in_progress");
  await assert.rejects(() => cases.action(merchantId, next.ticketId, "operator_qa", { action: "reject", notes: "   " }), /resolution_notes_required/);
  await cases.action(merchantId, next.ticketId, "operator_qa", { action: "reject", notes: "Cliente optou por uma troca do item B após análise na conversa." });
  assert.equal((await cases.detail(merchantId, next.ticketId)).active, false);
  const rejectionNotices = await db.returnNoticeDelivery.findMany({ where: { returnId: next.returnId, type: "return_rejected" } });
  assert.equal(rejectionNotices.length, 2);
  assert.deepEqual(new Set(rejectionNotices.map(row => row.channel)), new Set(["email", "whatsapp"]));
  assert.ok(rejectionNotices.every(row => (row.payload as any).explanation.includes("Cliente optou")));
  assert.ok(rejectionNotices.every(row => (row.payload as any).items.length === 2));
  const exchange = await cases.open({ ...input, kind: "exchange", requestKey: randomUUID(), items: [{ variantId: "variant_b", quantity: 1 }] });
  await assert.rejects(() => cases.action(merchantId, exchange.ticketId, "operator_qa", { action: "complete_exchange", notes: "Ainda em análise", replacementOrderId: "replacement_qa", trackingCode: "tracking_qa" }), /replacement_and_delivery_required/);
  await cases.action(merchantId, exchange.ticketId, "operator_qa", { action: "authorize_return", notes: "Entregue o item na loja; entraremos em contato ao receber." });
  await cases.action(merchantId, exchange.ticketId, "operator_qa", { action: "received", notes: "Recebemos uma unidade do item B." });
  await cases.action(merchantId, exchange.ticketId, "operator_qa", { action: "inspection_pass", notes: "Item conferido com o relato do cliente.", itemCondition: "GOOD" });
  await cases.action(merchantId, exchange.ticketId, "operator_qa", { action: "complete_exchange", notes: "Cliente confirmou o recebimento da reposição.", replacementOrderId: "replacement_qa", trackingCode: "tracking_qa", deliveryConfirmed: true });
  assert.equal((await cases.detail(merchantId, exchange.ticketId)).returnStatus, "EXCHANGE_COMPLETED");
  assert.equal((await orders.load(merchantId, orderId, buyerId)).items.find(item => item.variantId === "variant_b")!.eligibleQuantity, 0);
  const cancelled = await cases.open({ ...input, requestKey: randomUUID() });
  await assert.rejects(() => cases.action(merchantId, cancelled.ticketId, "operator_qa", { action: "cancel" }), /resolution_notes_required/);
  await cases.action(merchantId, cancelled.ticketId, "operator_qa", { action: "cancel", notes: "Cancelamento confirmado com o cliente na conversa." });
  const cancelledCase = await cases.detail(merchantId, cancelled.ticketId);
  assert.equal(cancelledCase.active, false); assert.equal(cancelledCase.status, "resolved");
  assert.ok(cancelledCase.messages.some(message => message.content.includes("Cancelamento confirmado")));
  const genericKey = randomUUID();
  const generic = await Promise.all(Array.from({ length: 5 }, () => cases.genericOpen(merchantId, buyerId, "Ajuda com minha compra", genericKey)));
  assert.equal(new Set(generic.map(item => item.ticketId)).size, 1);
  assert.equal(await db.supportTicketMessage.count({ where: { ticketId: generic[0]!.ticketId, senderType: "buyer", clientMessageId: genericKey } }), 1);
  await t.test("legacy writes after migration recover ownership and aliases exactly once", async () => {
    const legacy = await db.return.create({ data: { merchantId, buyerId, orderId: `legacy_${suffix}`, reason: "OTHER", imageUrls: [], notes: "Relato histórico preservado", items: { create: [{ variantId: "legacy_variant", quantity: 1 }] } } });
    const canonicalId = `legacy_canonical_${suffix}`, duplicateId = `legacy_duplicate_${suffix}`;
    await db.supportTicket.create({ data: { id: canonicalId, merchantId, returnId: legacy.id, buyerMessage: "Abertura histórica do cliente", source: "return_request", status: "open", createdAt: new Date(), updatedAt: new Date() } });
    await db.supportTicket.create({ data: { id: duplicateId, merchantId, sessionId: legacy.id, buyerMessage: "Abertura histórica do cliente", source: "return_request", status: "open", createdAt: new Date(), updatedAt: new Date() } });
    await db.supportTicketMessage.create({ data: { ticketId: duplicateId, senderType: "buyer", content: "Abertura histórica do cliente" } });
    await db.supportTicketMessage.create({ data: { ticketId: duplicateId, senderType: "merchant", content: "Resposta histórica da loja" } });
    await assert.rejects(() => cases.buyerTicket("another_buyer", duplicateId), /ticket_not_found/);
    await assert.rejects(() => cases.buyerTicket(buyerId, duplicateId, "another_merchant"), /ticket_not_found/);
    assert.equal((await db.supportTicket.findUniqueOrThrow({ where: { id: canonicalId } })).buyerId, null);
    assert.equal((await cases.buyerTicket(buyerId, duplicateId, merchantId)).id, canonicalId);
    await Promise.all(Array.from({ length: 4 }, () => cases.forReturn(merchantId, legacy.id)));
    const recovered = await cases.detail(merchantId, canonicalId);
    assert.ok(recovered.messages.some(message => message.content === "Resposta histórica da loja"));
    assert.equal(recovered.messages.filter(message => message.content === "Abertura histórica do cliente").length, 1);
    assert.equal(recovered.messages.filter(message => message.content.startsWith("Sua solicitação foi recuperada.")).length, 1);
    assert.equal((await db.supportTicket.findUniqueOrThrow({ where: { id: duplicateId } })).mergedIntoId, canonicalId);
    const listed = await cases.list(buyerId, merchantId);
    assert.equal(listed.items.filter(item => item.returnId === legacy.id).length, 1);
    assert.equal(posts, 1);
  });
  await t.test("hub recovers an old return with no canonical ticket without creating duplicates", async () => {
    const legacy = await db.return.create({ data: { merchantId, buyerId, orderId: `legacy_hub_${suffix}`, reason: "OTHER", imageUrls: [], items: { create: [{ variantId: "legacy_variant", quantity: 1 }] } } });
    const oldId = `legacy_hub_ticket_${suffix}`;
    await db.supportTicket.create({ data: { id: oldId, merchantId, sessionId: legacy.id, buyerMessage: "Pedido histórico", source: "return_request", status: "open", createdAt: new Date(), updatedAt: new Date() } });
    const first = await cases.list(buyerId, merchantId);
    const second = await cases.list(buyerId, merchantId);
    const recovered = first.items.find(item => item.returnId === legacy.id)!;
    assert.ok(recovered);
    assert.equal(recovered.ticketId, oldId);
    assert.equal(second.items.filter(item => item.returnId === legacy.id).length, 1);
    assert.equal((await cases.buyerTicket(buyerId, oldId)).id, recovered.ticketId);
    assert.equal(await db.supportTicket.count({ where: { merchantId, returnId: legacy.id, mergedIntoId: null } }), 1);
    assert.equal((await cases.detail(merchantId, recovered.ticketId)).messages.length, 2);
    assert.equal(posts, 1);
  });
  await t.test("legacy recovery never reassigns a ticket already owned by another buyer", async () => {
    const legacy = await db.return.create({ data: { merchantId, buyerId, orderId: `legacy_conflict_${suffix}`, reason: "OTHER", imageUrls: [] } });
    const id = `legacy_foreign_${suffix}`;
    await db.supportTicket.create({ data: { id, merchantId, buyerId: "another_buyer", returnId: legacy.id, buyerMessage: "Conflicting ownership", source: "return_request", status: "open", createdAt: new Date(), updatedAt: new Date() } });
    await assert.rejects(() => cases.forReturn(merchantId, legacy.id), /return_ticket_buyer_mismatch/);
    await assert.rejects(() => cases.buyerTicket(buyerId, id), /ticket_not_found/);
    assert.equal((await db.supportTicket.findUniqueOrThrow({ where: { id } })).buyerId, "another_buyer");
    assert.ok(!(await cases.list(buyerId, merchantId)).items.some(item => item.ticketId === id));
  });
  const repo = new PrismaReturnRepository(db);
  await repo.saveRefund({ returnId, status: "PENDING", amountInCents: 1000 });
  await repo.updateRefundStatus(returnId, "FAILED", new Date());
  assert.equal((await repo.findById(merchantId, returnId))!.refund!.status, "COMPLETED");
});
