import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaCheckoutRepository } from "../src/modules/checkout/infrastructure/prisma/prisma-checkout.repository.js";
const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL }) });
const repo = new PrismaCheckoutRepository(prisma as any);
const sessions = await repo.findSessionsWithTrigger();
const diego = sessions.find((s: any) => s.sessionId === "test_rec_diego_001");
console.log("total candidates:", sessions.length);
console.log("diego in candidates:", !!diego);
if (diego) console.log("diego globalUserId:", (diego as any).globalUserId, "score:", (diego as any).abandonmentScore);
await prisma.$disconnect();
