/**
 * Test embed integration flow end-to-end.
 *
 * Run: cd apps/api && npx tsx scripts/test-embed-integration.ts
 * Requires: API on localhost:3009
 *
 * Flow: Login → Create API Key → Generate Embed Token → Output snippet
 */

import http from "node:http";

const API = "http://localhost:3009";
const EMAIL = "costaadiego1989@gmail.com";
const PASS = "UeUf3900@";

function post(path: string, body: string, cookie?: string): Promise<{ status: number; data: any; cookie?: string }> {
  return new Promise((resolve, reject) => {
    const req = http.request(`${API}${path}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Content-Length": Buffer.byteLength(body).toString(),
        "Idempotency-Key": `idk_${Date.now()}_${Math.random().toString(36).slice(2, 10)}`,
        ...(cookie ? { Cookie: cookie } : {}),
      },
    }, (res) => {
      let data = "";
      res.on("data", (c) => data += c);
      res.on("end", () => {
        const setCookie = res.headers["set-cookie"]?.[0]?.split(";")[0];
        try { resolve({ status: res.statusCode!, data: JSON.parse(data), cookie: setCookie }); }
        catch { resolve({ status: res.statusCode!, data, cookie: setCookie }); }
      });
    });
    req.on("error", reject);
    req.write(body);
    req.end();
  });
}

async function run() {
  console.log("🧪 EMBED INTEGRATION E2E TEST\n");

  // 1. Login
  console.log("1️⃣  Login...");
  const login = await post("/auth/login", JSON.stringify({ email: EMAIL, password: PASS }));
  if (login.status !== 200 && login.status !== 201) {
    console.log(`   ❌ Login failed: ${login.status}`, JSON.stringify(login.data).substring(0, 100));
    process.exit(1);
  }
  const cookie = login.cookie!;
  const merchantId = login.data.merchantId;
  console.log(`   ✅ Logged in as: ${merchantId}`);

  // 2. Create API key (with embed scope)
  console.log("\n2️⃣  Create API key...");
  const keyBody = JSON.stringify({
    name: `Embed Key ${new Date().toISOString().slice(0, 10)}`,
    scopes: ["checkout:read", "checkout:write", "embed:sessions:create", "orders:read", "catalog:read"],
    environment: "test",
  });
  const key = await post("/integrations/api-keys", keyBody, cookie);
  if (key.status !== 200 && key.status !== 201) {
    console.log(`   ❌ Key creation failed: ${key.status}`, JSON.stringify(key.data).substring(0, 150));
    process.exit(1);
  }
  const secretKey = key.data.secret_key;
  console.log(`   ✅ Key: ${key.data.api_key?.id}`);
  console.log(`   🔑 Secret: ${secretKey.substring(0, 25)}...`);

  // 3. Generate embed session token (using session cookie — simulates backend call)
  console.log("\n3️⃣  Generate embed session token...");
  const tokenBody = JSON.stringify({
    ttl_seconds: 3600,
    allowed_origin: "http://localhost:3001",
    scopes: ["checkout:start", "checkout:track", "checkout:chat", "offers:apply"],
  });
  const token = await post("/embed-sessions", tokenBody, cookie);
  if (token.status !== 200 && token.status !== 201) {
    console.log(`   ❌ Token generation failed: ${token.status}`, JSON.stringify(token.data).substring(0, 150));
    console.log("   ℹ️  This endpoint may require API key auth instead of session cookie.");
    console.log("   ℹ️  The snippet still works — token is generated by merchant's backend.");
  } else {
    const embedToken = token.data.token ?? token.data.embed_session_token;
    console.log(`   ✅ Token: ${embedToken?.substring(0, 40)}...`);
    console.log(`   ⏱️  Expires: ${token.data.expires_at ?? token.data.expires_at_unix}`);

    // 4. Output complete snippet
    console.log("\n════════════════════════════════════════");
    console.log("✅ SNIPPET PRONTO PARA USAR:\n");
    console.log(`<script src="${API}/widget/aacp.js" async></script>`);
    console.log(`<zyon-checkout-agent`);
    console.log(`  merchant-id="${merchantId}"`);
    console.log(`  api-base-url="${API}"`);
    console.log(`  embed-session-token="${embedToken}"`);
    console.log(`></zyon-checkout-agent>`);
    console.log("\n════════════════════════════════════════");
  }

  // Summary
  console.log("\n📋 RESUMO:");
  console.log(`   Merchant: ${merchantId}`);
  console.log(`   API Key: ${secretKey.substring(0, 25)}...`);
  console.log(`   Endpoint token: POST ${API}/embed-sessions`);
  console.log(`   Auth: Authorization: Bearer ${secretKey.substring(0, 15)}...`);
}

run().catch((e) => {
  console.error("❌ Error:", e.message);
  process.exit(1);
});
