import { useEffect, useMemo, useRef, useState } from "react";
import type {
  ApplyOfferResponse,
  ChatMessageResponse,
  ChatTurn,
  SuggestedProduct
} from "@aacp/shared-types";
import {
  checkoutJson,
  CHECKOUT_EMBED_PATHS,
  CHECKOUT_LEGACY_PATHS
} from "../lib/embed-client.js";
import {
  applyCouponResponseSchema,
  applyOfferResponseSchema,
  chatMessageResponseSchema,
  crossSellAcceptResponseSchema
} from "../lib/widget-schemas.js";
import type { WidgetConfig } from "../lib/widget-types.js";
import { bubbleKey, type QuickReplyChoice } from "./checkout-view-model.js";
import { disableStreamingByEnv } from "./use-streamed-text.js";
import type { CheckoutSessionState } from "./use-checkout-session.js";

const DEFAULT_QUICK_REPLIES: QuickReplyChoice[] = [
  { label: "Olá!" },
  { label: "Quero começar" },
  { label: "Quero finalizar agora" },
];

export function useCheckoutChat(config: WidgetConfig, sessionState: CheckoutSessionState) {
  const { session, activeExperience, syncExperience, networkError, apiOrigin, embedOpts } = sessionState;
  const isConversational = config.uiPresentation === "conversational";

  const [turns, setTurns] = useState<ChatTurn[]>([]);
  const [message, setMessage] = useState("");
  const [lastChat, setLastChat] = useState<ChatMessageResponse | null>(null);
  const [busy, setBusy] = useState(false);
  const [coupon, setCoupon] = useState("");
  const [streamingTurnKey, setStreamingTurnKey] = useState<string | null>(null);
  const [streamingDoneKey, setStreamingDoneKey] = useState<string | null>(null);

  const threadRef = useRef<HTMLDivElement | null>(null);
  const composerInputRef = useRef<HTMLInputElement | null>(null);
  const prevStreamingTurnKey = useRef<string | null>(null);
  const prevStartTs = useRef(0);
  const registrationPromptTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const checkoutStage = useMemo(() => {
    if (activeExperience.stage === "completed") return "completed";
    const apiStage = lastChat?.stage ?? activeExperience.stage;
    return apiStage ?? "data_collection";
  }, [activeExperience.stage, lastChat?.stage]);

  const awaitingAgentPlayback = !disableStreamingByEnv() && streamingTurnKey !== null && streamingDoneKey !== streamingTurnKey;
  const composerLocked = busy || Boolean(networkError);

  const quickReplies = useMemo((): QuickReplyChoice[] => {
    if (!isConversational || turns.length < 1 || busy) return [];
    const list: QuickReplyChoice[] = [];

    if (!lastChat) {
      // No API chat response yet — show default starters + experience quick replies from /start
      list.push(...DEFAULT_QUICK_REPLIES);
      if (activeExperience.copy.quick_replies.length > 0) {
        list.push(...activeExperience.copy.quick_replies.map((label) => ({ label })));
      }
    } else {
      // After first API chat response, use ONLY API-provided quick replies (stage-contextual)
      if (lastChat.actions?.length) {
        list.push(...lastChat.actions.map((a) => ({ label: a.label, type: a.type as never, offerId: a.offer_id })));
      }
      // Add experience quick replies (generated by API based on current stage + missing fields)
      if (activeExperience.copy.quick_replies.length > 0) {
        list.push(...activeExperience.copy.quick_replies.map((label) => ({ label })));
      }
      // Inject approved-offer chip if not already present
      if (lastChat.authorized_offer?.approved && !list.some((r) => /desconto/i.test(r.label ?? ""))) {
        const offer = lastChat.authorized_offer;
        const pct = offer.type === "discount_percent" ? offer.value : 0;
        if (pct > 0 && offer.id) {
          list.push({ label: `Aplicar desconto de ${pct}%`, offerId: offer.id });
        }
      }
    }

    // Deduplicate
    const seen = new Set<string>();
    return list.filter((r) => {
      const key = (r.label ?? "").trim();
      if (!key || seen.has(key)) return false;
      seen.add(key);
      return true;
    });
  }, [activeExperience.copy.quick_replies, isConversational, lastChat, busy, turns.length]);

  useEffect(() => {
    if (streamingTurnKey == null) return;
    if (prevStreamingTurnKey.current === streamingTurnKey) return;
    prevStreamingTurnKey.current = streamingTurnKey;
    setStreamingDoneKey(null);
  }, [streamingTurnKey]);

  useEffect(() => {
    return () => {
      if (registrationPromptTimer.current) {
        clearTimeout(registrationPromptTimer.current);
        registrationPromptTimer.current = null;
      }
    };
  }, []);

  useEffect(() => {
    const el = threadRef.current;
    if (!el) return;
    const scrollToBottom = () => {
      el.scrollTop = el.scrollHeight;
    };
    scrollToBottom();
    window.requestAnimationFrame?.(scrollToBottom);
  }, [turns.length, busy, streamingTurnKey, streamingDoneKey, quickReplies.length, checkoutStage]);

  useEffect(() => {
    const showComposer = isConversational && Boolean(session) && !networkError && checkoutStage !== "completed" && checkoutStage !== "payment";
    if (!showComposer) return;
    composerInputRef.current?.focus();
  }, [isConversational, session, networkError, checkoutStage]);

  useEffect(() => {
    if (!isConversational || !session || networkError || busy || checkoutStage === "completed" || checkoutStage === "payment") return;
    composerInputRef.current?.focus();
  }, [awaitingAgentPlayback, busy, isConversational, session, networkError, checkoutStage]);

  // Initialize turns from /start response
  useEffect(() => {
    const ev = sessionState.startedEvent;
    if (!ev || ev.ts === prevStartTs.current) return;
    prevStartTs.current = ev.ts;

    const response = ev.response;
    if (registrationPromptTimer.current) {
      clearTimeout(registrationPromptTimer.current);
      registrationPromptTimer.current = null;
    }
    if (Array.isArray(response.turns) && response.turns.length > 0) {
      setTurns(response.turns);
      const lastAgentIdx = response.turns.map((t) => t.role).lastIndexOf("agent");
      if (lastAgentIdx >= 0) {
        setStreamingTurnKey(bubbleKey(response.turns[lastAgentIdx]!, lastAgentIdx));
      }
    } else {
      const greeting: ChatTurn = {
        role: "agent",
        text: response.experience.agent.greeting,
        occurredAt: new Date().toISOString()
      };
      setTurns([greeting]);
      setStreamingTurnKey(bubbleKey(greeting, 0));
      registrationPromptTimer.current = setTimeout(() => {
        registrationPromptTimer.current = null;
        const regTurn: ChatTurn = {
          role: "agent",
          text: "Antes de começar, preciso fazer o seu cadastro. Qual é o seu nome completo?",
          occurredAt: new Date().toISOString()
        };
        setTurns((curr) => {
          if (curr.length === 1 && curr[0]!.text === greeting.text) {
            setStreamingTurnKey(bubbleKey(regTurn, 1));
            return [...curr, regTurn];
          }
          return curr;
        });
      }, 1500);
    }
    if (response.initial_mode === "open") {
      // compositor handles setOpen
    }
  }, [sessionState.startedEvent]);

  // Network error → reset turns to fallback greeting
  useEffect(() => {
    if (!sessionState.startErrorTs) return;
    const fallbackTurn: ChatTurn = {
      role: "agent",
      text: "Estou tentando conectar com a API da loja para carregar seu pedido real.",
      occurredAt: new Date().toISOString()
    };
    setTurns([fallbackTurn]);
    setStreamingTurnKey(bubbleKey(fallbackTurn, 0));
  }, [sessionState.startErrorTs]);

  // Auto-trigger registration for conversational mode
  useEffect(() => {
    if (isConversational && session && turns.length === 1 && !config.customer?.fullName && !busy && !networkError && !disableStreamingByEnv()) {
      const timer = setTimeout(() => { void autoTriggerRegistration(); }, 1500);
      return () => clearTimeout(timer);
    }
  }, [session, turns.length, isConversational, busy, networkError, config.customer?.fullName]);

  function appendAgentTurn(text: string, opts: { stream?: boolean } = {}): void {
    const turn: ChatTurn = { role: "agent", text, occurredAt: new Date().toISOString() };
    setTurns((current) => {
      const next = [...current, turn];
      if (opts.stream) setStreamingTurnKey(bubbleKey(turn, next.length - 1));
      return next;
    });
  }

  function handleAgentTypingDone(key: string): void {
    if (streamingTurnKey === key) setStreamingDoneKey(key);
  }

  function applyTurnResponse(response: ChatMessageResponse): void {
    sessionState.setNetworkError?.(null);
    setLastChat(response);
    if (response.experience) syncExperience(response.experience);
    if (Array.isArray(response.turns) && response.turns.length > 0) {
      setTurns(response.turns);
      for (let i = response.turns.length - 1; i >= 0; i--) {
        if (response.turns[i]!.role === "agent") {
          setStreamingTurnKey(bubbleKey(response.turns[i]!, i));
          break;
        }
      }
    } else {
      appendAgentTurn(response.message, { stream: true });
    }
  }

  async function sendMessageWithOverride(userText: string): Promise<void> {
    if (!session || networkError || !userText.trim() || composerLocked) return;
    setBusy(true);
    setTurns((current) => [...current, { role: "buyer", text: userText.trim(), occurredAt: new Date().toISOString() }]);
    try {
      const paths = config.mode === "embed" ? CHECKOUT_EMBED_PATHS : CHECKOUT_LEGACY_PATHS;
      const body = config.mode === "embed"
        ? { session_id: session.session_id, conversation_id: session.conversation_id, user_message: userText.trim() }
        : { merchant_id: config.merchantId, session_id: session.session_id, conversation_id: session.conversation_id, user_message: userText.trim() };
      const response = await checkoutJson<ChatMessageResponse>(apiOrigin, paths.chatMessage, {
        ...embedOpts,
        body,
        schema: chatMessageResponseSchema
      });
      applyTurnResponse(response);
      setMessage("");
    } catch {
      sessionState.setNetworkError?.("Falha ao falar com a IA. Tente novamente em instantes.");
    } finally {
      setBusy(false);
    }
  }

  async function sendMessage(): Promise<void> {
    const userText = message.trim();
    if (!session || !userText) return;
    setMessage("");
    await sendMessageWithOverride(userText);
  }

  async function autoTriggerRegistration(): Promise<void> {
    if (!session || networkError || composerLocked) return;
    setBusy(true);
    try {
      const paths = config.mode === "embed" ? CHECKOUT_EMBED_PATHS : CHECKOUT_LEGACY_PATHS;
      const body = config.mode === "embed"
        ? { session_id: session.session_id, conversation_id: session.conversation_id, user_message: "Iniciar cadastro" }
        : { merchant_id: config.merchantId, session_id: session.session_id, conversation_id: session.conversation_id, user_message: "Iniciar cadastro" };
      const response = await checkoutJson<ChatMessageResponse>(apiOrigin, paths.chatMessage, {
        ...embedOpts,
        body,
        schema: chatMessageResponseSchema
      });
      applyTurnResponse(response);
    } catch {
      sessionState.setNetworkError?.("Falha ao falar com a IA. Tente novamente em instantes.");
    } finally {
      setBusy(false);
    }
  }

  async function applyOfferById(offerId?: string): Promise<void> {
    if (!session) return;
    const targetOffer =
      offerId && lastChat?.authorized_offer?.id === offerId
        ? lastChat.authorized_offer
        : lastChat?.authorized_offer;
    if (!targetOffer) return;
    setBusy(true);
    try {
      const paths = config.mode === "embed" ? CHECKOUT_EMBED_PATHS : CHECKOUT_LEGACY_PATHS;
      const body = config.mode === "embed"
        ? { session_id: session.session_id, offer_id: targetOffer.id }
        : { merchant_id: config.merchantId, session_id: session.session_id, offer_id: targetOffer.id };
      const response = await checkoutJson<ApplyOfferResponse>(apiOrigin, paths.applyOffer, {
        ...embedOpts,
        body,
        schema: applyOfferResponseSchema
      });
      if (response.experience) syncExperience(response.experience);
      if (response.agent_turn) {
        setTurns((current) => {
          const next = [...current, response.agent_turn as ChatTurn];
          setStreamingTurnKey(bubbleKey(next[next.length - 1]!, next.length - 1));
          return next;
        });
      } else {
        appendAgentTurn(
          response.success
            ? `Oferta aplicada. Codigo: ${response.discount_code ?? "gerado"}.`
            : `Não consegui aplicar a oferta: ${response.reason ?? "erro desconhecido"}.`,
          { stream: true }
        );
      }
    } finally {
      setBusy(false);
    }
  }

  async function tapQuick(reply: QuickReplyChoice): Promise<void> {
    if (!session || networkError || composerLocked) return;
    if (reply.event) void sessionState.track(reply.event);
    if (reply.type === "apply_offer") {
      await applyOfferById(reply.offerId);
      return;
    }
    await sendMessageWithOverride(reply.label);
  }

  async function continueToPayment(): Promise<void> {
    await sendMessageWithOverride("Quero seguir para o pagamento.");
  }

  async function acceptCrossSell(product: SuggestedProduct): Promise<boolean> {
    if (!session || networkError || composerLocked || !product.suggestion_id) return false;
    setBusy(true);
    setTurns((current) => [...current, { role: "buyer", text: `Adicionar ${product.name}`, occurredAt: new Date().toISOString() }]);
    try {
      const paths = config.mode === "embed" ? CHECKOUT_EMBED_PATHS : CHECKOUT_LEGACY_PATHS;
      const response = await checkoutJson<{
        suggestion: unknown;
        experience?: typeof activeExperience;
        agent_turn?: ChatTurn;
      }>(
        apiOrigin,
        paths.acceptCrossSell,
        {
          ...embedOpts,
          body: {
            session_id: session.session_id,
            suggestion_id: product.suggestion_id,
            accepted_skus: [product.sku]
          },
          schema: crossSellAcceptResponseSchema
        }
      );
      if (response.experience) syncExperience(response.experience);
      if (response.agent_turn) {
        setTurns((current) => {
          const next = [...current, response.agent_turn as ChatTurn];
          setStreamingTurnKey(bubbleKey(next[next.length - 1]!, next.length - 1));
          return next;
        });
      } else {
        appendAgentTurn(`${product.name} adicionado ao seu pedido.`, { stream: true });
      }
      return true;
    } catch {
      sessionState.setNetworkError?.("Falha ao adicionar o complemento. Tente novamente em instantes.");
      return false;
    } finally {
      setBusy(false);
    }
  }

  async function submitCoupon(): Promise<boolean> {
    const code = coupon.trim();
    if (!code || !session) return false;
    setCoupon("");
    setBusy(true);
    setTurns((current) => [...current, { role: "buyer", text: `Cupom: ${code}`, occurredAt: new Date().toISOString() }]);
    try {
      const paths = config.mode === "embed" ? CHECKOUT_EMBED_PATHS : CHECKOUT_LEGACY_PATHS;
      const body: Record<string, unknown> = {
        session_id: session.session_id,
        merchant_id: config.merchantId,
        code,
        cart: {
          currency: activeExperience.totals.currency,
          total: activeExperience.totals.subtotal,
          currentDiscount: activeExperience.totals.discount,
          items: activeExperience.items.map((item) => ({
            sku: item.sku,
            name: item.name,
            price: item.unit_price,
            quantity: item.quantity,
            category: item.category,
            variant: item.variant,
            imageUrl: item.image_url,
            productUrl: item.product_url
          }))
        }
      };
      const response = await checkoutJson<{ redemption_id: string; discount_applied: number; coupon: unknown; experience?: typeof activeExperience }>(
        apiOrigin,
        paths.applyCoupon,
        { ...embedOpts, body, schema: applyCouponResponseSchema }
      );
      if (response.experience) syncExperience(response.experience);
      appendAgentTurn(
        `Cupom ${code.toUpperCase()} aplicado! Desconto de R$${response.discount_applied.toFixed(2)}.`,
        { stream: true }
      );
      return true;
    } catch (err) {
      const msg = err instanceof Error ? err.message : "";
      let userMsg = "Cupom inválido. Verifique o código e tente novamente.";
      if (msg.includes("404") || msg.includes("COUPON_NOT_FOUND")) {
        userMsg = "Cupom não encontrado. Verifique o código e tente novamente.";
      } else if (msg.includes("409") || msg.includes("COUPON_ALREADY_APPLIED")) {
        userMsg = "Este cupom já foi aplicado nesta sessão.";
      } else if (msg.includes("400")) {
        userMsg = "Cupom inválido ou expirado. Verifique e tente novamente.";
      }
      appendAgentTurn(userMsg, { stream: true });
      return false;
    } finally {
      setBusy(false);
    }
  }

  function retryChat(): void {
    sessionState.retryStartCheckout();
    setTurns([]);
    setLastChat(null);
  }

  return {
    turns,
    message,
    setMessage,
    lastChat,
    busy,
    coupon,
    setCoupon,
    streamingTurnKey,
    threadRef,
    composerInputRef,
    checkoutStage,
    composerLocked,
    awaitingAgentPlayback,
    quickReplies,
    appendAgentTurn,
    handleAgentTypingDone,
    sendMessage,
    sendMessageWithOverride,
    tapQuick,
    applyOffer: () => applyOfferById(lastChat?.authorized_offer?.id),
    continueToPayment,
    acceptCrossSell,
    submitCoupon,
    retryChat,
  };
}

export type CheckoutChatState = ReturnType<typeof useCheckoutChat>;
